export {Header} from "./Header/Header"
export {Hero} from "./Hero/Hero"
export {KeyServices} from "./KeyServices/KeyServices"
export {ComponentsDevelopment} from "./ComponentsDevelopment/ComponentsDevelopment"
export {PageDevelopment} from "./PageDevelopment/PageDevelopment"
export {Pricing} from "./Pricing/Pricing"
export {WorkWithUs} from "./WorkWithUs/WorkWithUs"
export {Footer} from "./Footer/Footer"